name: End-to-End Tests
on: [push]
jobs:
  test:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
      - run: npm install
      - run: npm run e2eHeadless
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: reports/report.xml
